//
//  MainWeatherSceneInteractor.swift
//  CleanWeatherApp
//
//  Created by Игорь Корабельников on 26.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainWeatherSceneBusinessLogic
{
  func doSomething(request: MainWeatherScene.Something.Request)
}

protocol MainWeatherSceneDataStore
{
  //var name: String { get set }
}

class MainWeatherSceneInteractor: MainWeatherSceneBusinessLogic, MainWeatherSceneDataStore
{
  var presenter: MainWeatherScenePresentationLogic?
  var worker: MainWeatherSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MainWeatherScene.Something.Request)
  {
    worker = MainWeatherSceneWorker()
    worker?.doSomeWork()
    
    let response = MainWeatherScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
